### ISSUE TITLE
Switch the cache to web_poet.serialization

### ISSUE THREAD

**Issue by wRAR** [scrapinghub/scrapy-poet#105]
We've investigated the possibility to use `web_poet.serialization` for the scrapy-poet cache, either by replacing the existing implementation completely (it would include replacing the API as currently providers are responsible for (de)serialization) or by only using the web-poet code to (de)serialize `HttpResponse`. Currently in scrapy-poet only `HttpResponseProvider` supports caching, but the web-poet implementation supports more dependency types and so replacing the implementation completely looks useful but isn't straightforward. The unanswered questions I see so far:

1. If we e.g. write a web-poet-based replacement of `SqlitedictCache` to store just `HttpResponse` (if it's possible), will it help as a first step in the migration? I suspect that it won't.
2. If we need to change the provider API, by changing or removing `CacheDataProviderMixin`, what will this break?
3. What should be the keys in the new cache? Currently the key includes the provider name and the request fingerprint calculated by the provider.
4. We may need to change/add something at the web-poet side, e.g. add a function that returns a list of deps instead of returning a reconstructed PO (which `serialize()` does). We may also need compressed storage support, we already have a place to implement pluggable storages (as alternatives compatible with `SerializedDataFileStorage`).
5. Also changing the caching interface requires rewriting of `Injector.build_instances_from_providers`, though this part may actually be easy when the new interface is clear.

**Comment by lampssy** [comment]
@wRAR as discussed, I'll be working on this issue
