### ISSUE TITLE
Problem with ItemLoader

### ISSUE THREAD

**Issue by maranqz** [scrapinghub/scrapy-poet#12]
If we use Page Object (WebPage) wiht ItemLoader, code give exception.
AttributeError: 'ResponseData' object has no attribute 'text'.

Temporary fixed by
```
@provides(Response)
class ResponseProvider(PageObjectInputProvider):

    def __init__(self, response: Response):
        self.response = response

    def __call__(self):
        return self.response
```

**Comment by kmike** [comment]
Currently the plan is to move item loaders to a a separate library, to make it easier to integrate with scrapy-po. See https://github.com/scrapy/scrapy/issues/4005

**Comment by kmike** [comment]
Itemloaders are extracted to a separate library now: https://github.com/scrapy/itemloaders
