### ISSUE TITLE
ItemProvider always requires Response

### ISSUE THREAD

**Issue by kmike** [scrapinghub/scrapy-poet#150]
Currently ItemProvider always requires Response. So, if a page object doesn't need a response, and an item produced by this page object is used as a dependency, then Response is still downloaded.

**Comment by wRAR** [comment]
As ItemProvider only needs `Response` to pass it to `build_instances` we discussed the idea that just passing a `DummyResponse` instance there can be enough but didn't check that.

**Comment by Gallaecio** [comment]
Resolved by https://github.com/scrapinghub/scrapy-poet/pull/175
