### ISSUE TITLE
Stats for POs

### ISSUE THREAD

**Issue by proway2** [scrapinghub/scrapy-poet#158]
Produce stats for every page object that's being injected during the run. Stats should look like:

```
scrapy-poet/page-objects/my_project.page.AmazonProductPage 56
scrapy-poet/page-objects/my_project.page.AmazonListingPage 15
```

**Comment by proway2** [comment]
For the sake of consistency this approach is actually being implemented:
```
scrapy_poet/page_objects/my_project/page/AmazonProductPage 56
scrapy_poet/page_objects/my_project/page/AmazonListingPage 15
```

**Comment by Gallaecio** [comment]
I am not against the original proposal. It made it clear that it was an import path, which might not be clear with the new proposal.

**Comment by proway2** [comment]
The problem is that dots are removed when the data is stored in MMR.

**Comment by Gallaecio** [comment]
@VMRuiz Why do you hate dots so much?! :P

**Comment by proway2** [comment]
As per the discussion with @kmike we're going to use dots here :-)

**Comment by VMRuiz** [comment]
> @VMRuiz Why do you hate dots so much?! :P

I promise is not me. Blame external factors.
