### ISSUE TITLE
Auto-populate fields on Item Overrides

### ISSUE THREAD

**Issue by BurnzZ** [scrapinghub/scrapy-poet#168]
Following the https://github.com/scrapinghub/scrapy-poet/pull/164 PR being merged, we can now override items from providers _(e.g. from scrapy-zyte-api's `ZyteApiProvider`):_

```python
import attrs
from zyte_common_items import Product
from web_poet import handle_urls, WebPage, field

@handle_urls("example.com")
@attrs.define 
class ProductPage(WebPage[Product]):
    product: Product

    @field
    def name(self) -> str:
        return f"(modified) {self.product.name}"
```

The common use case for this are fixing or modifying fields. However, if the item in question has a lot of fields, the Page Object code could be convoluted:

```python
@handle_urls("example.com")
@attrs.define 
class ProductPage(WebPage[Product]):
    product: Product

    @field
    def name(self) -> str:
        return f"(modified) {self.product.name}"

    @field
    def brand(self) -> str:
        return self.product.brand

    @field
    def color(self) -> str:
         return self.product.color

    # and so on for the rest of the unmodified fields ...
```

We should provide/document an easy way to go about this. It'd be great if there are some built-in way to do this such that we don't have to re-iterate all of the unmodified fields with such boilerplate code.

An idea:
- Decorator for the Page Object which auto-populates the item when `to_item()` is called. A bit tricky when individual fields are called. Also need to ensure the item validation mechanism is correct.

**Comment by kmike** [comment]
It might also belong to zyte-common-items repo.

**Comment by kmike** [comment]
Or to scrapy-zyte-api :)

**Comment by Gallaecio** [comment]
Solved by https://github.com/zytedata/zyte-common-items/pull/63.
