### ISSUE TITLE
Make configuration documentation more visible

### ISSUE THREAD

**Issue by victor-torres** [scrapinghub/scrapy-poet#36]
Currently, it's not so easy to get to the configuration docs of scrapy-poet.

Today, you need to follow the following path to get basic installation instructions:

1. maybe open this git repository
2. open the read the docs page
3. access the installation guide

Even then, there are no configuration steps described in the installation guide. 
Users need to access the Tutorial and find the configuration steps described there.

Ideally, we should provide configuration docs right after the installation guide or as part of it.
Also, we should evaluate if isn't it better to provide this information right on the documentation front page to save the user from some additional clicks.

Source of this discussion: https://github.com/scrapinghub/scrapy-autoextract/pull/13#discussion_r473136308

**Comment by Gallaecio** [comment]
Solved by https://github.com/scrapinghub/scrapy-poet/pull/96
