### ISSUE TITLE
Unintended interaction with RobotsTxtMiddleware, FilesPipeline, and ImagePipeline

### ISSUE THREAD

**Issue by kmike** [scrapinghub/scrapy-poet#48]
When `def parse(self, response: DummyResponse):` annotation is used, downloading of robots.txt file is skipped; I'm not sure this is intended.

It seems it is cased by this code: https://github.com/scrapy/scrapy/blob/23cfdb058e80a18ee2b66e1b966355f3aca426d0/scrapy/downloadermiddlewares/robotstxt.py#L65 - RobotsTxtMiddleware uses scrapy.Request without setting a callback, which means "parse" by default, but in fact the callback is unused. Then injector inspects the callback signature and decides that response is not needed, while this signature is irrelevant, as the callback is never called.

**Comment by kmike** [comment]
It's actually worse than that: HttpClient stops working completely if `parse` method has `response: DummyResponse` annotation; the reason is the same.

For example, this works:

```py
import attrs
import scrapy
from scrapy_poet import DummyResponse
from web_poet import ItemPage, field, RequestUrl, HttpClient, cached_method


@attrs.define
class Book:
    title: str


@attrs.define
class BookPage(ItemPage[Book]):
    request_url: RequestUrl
    http: HttpClient

    @field
    async def title(self):
        response = await self.response()
        return response.css("h1::text").get()

    @cached_method
    async def response(self):
        url = str(self.request_url) + "858/index.html"
        return await self.http.get(url)


class ExampleSpider(scrapy.Spider):
    name = 'example'

    def start_requests(self):
        yield scrapy.Request('http://books.toscrape.com/catalogue/the-regional-office-is-under-attack_',
                             self.parse_book)

    async def parse_book(self, response: DummyResponse, page: BookPage):
        yield await page.to_item()

```

But if parse_book is renamed to parse, then it stops working.

**Comment by BurnzZ** [comment]
After looking more into Scrapy's code with similar a `Request` with an empty callback value, it would seem that `FilesPipeline` and `ImagePipeline` are affected as well. In particular, it stems from the `get_media_requests()` method: [files](https://github.com/scrapy/scrapy/blob/23cfdb058e80a18ee2b66e1b966355f3aca426d0/scrapy/pipelines/files.py#L487-L489) and [images](https://github.com/scrapy/scrapy/blob/23cfdb058e80a18ee2b66e1b966355f3aca426d0/scrapy/pipelines/images.py#L168-L170).

Here's a reproducible example:

```python
from scrapy import Request, Spider
from scrapy_poet import DummyResponse


class Robots(Spider):
    name = "robots"
    start_urls = ["https://books.toscrape.com"]

    custom_settings = {
        "ROBOTSTXT_OBEY": True,
        "DOWNLOADER_MIDDLEWARES": {
            "scrapy_poet.InjectionMiddleware": 543,
        },
        "ITEM_PIPELINES": {
            "scrapy.pipelines.files.FilesPipeline": 1,
        },
        "FILES_STORE": "/tmp/some/existing/path",
    }

    def parse(self, response: DummyResponse):
        return {"file_urls": ["https://books.toscrape.com/media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"]}
```

Unlike the issues mentioned previously by @kmike , this one doesn't produce any errors at all, only warnings:

```
2022-12-20 13:09:33 [scrapy_poet.downloadermiddlewares] DEBUG: Using DummyResponse instead of downloading <GET https://books.toscrape.com/media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg>
2022-12-20 13:09:33 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://books.toscrape.com/media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg> (referer: None)
2022-12-20 13:09:33 [scrapy.pipelines.files] WARNING: File (empty-content): Empty file from <GET https://books.toscrape.com/media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg> referred in <None>: no-content
2022-12-20 13:09:33 [scrapy.core.scraper] DEBUG: Scraped from <200 https://books.toscrape.com>
{'file_urls': ['https://books.toscrape.com/media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg'], 'files': []}
```

I'll update this comment after discovering other parts in Scrapy that are affected.
