### ISSUE TITLE
Discussion for subdomain overrides

### ISSUE THREAD

**Issue by BurnzZ** [scrapinghub/scrapy-poet#52]
### Background

Currently, the `@override_for` decorator only works for top-level domains. However, there are some cases wherein a site has multiple subdomains, usually per country _(where each has a slightly different layout)_. This is due to the current setup of `get_domain()` ([ref](https://github.com/scrapinghub/scrapy-poet/blob/master/scrapy_poet/utils.py#L8-L13)).

The problem lies in the following workaround due to limitations of the current `@override_for` decorator interface:

```python
@override_for("example.com", AutoExtractArticleListData)
@attr.s(auto_attribs=True)
class ExampleArticleListPage(AutoExtractItemWebPage):
    article_list_data: AutoExtractArticleListData

    def to_item(self) -> ArticleList:
    	article_list = self.article_list_data.to_item()

    	if "uk.example.com" in self.url:
    		return self._handle_uk(article_list)

    	elif "au.example.com" in self.url:
    		return self._handle_uk(article_list)

    	elif "fr.example.com" in self.url:
    		return self._handle_fr(article_list)

    	return article_list
```

### Objectives

I'm wondering if it's worth it to update the current interface with something like this?
```python
@override_for("example.com", AutoExtractArticleListData, subdomain="uk")
@override_for("example.com", AutoExtractArticleListData, subdomain="au")
@override_for("example.com", AutoExtractArticleListData, subdomain="fr")
```

Depending on the situation, this provides another option on how to structure the collection of PageObjects in the project.

**Comment by ivanprado** [comment]
I've proposed a change to default overrides configuration that allows configuring overrides for subdomains among other things. https://github.com/scrapinghub/scrapy-poet/pull/53 . 

Once merged, it will allow:

```py
@override_for("uk.example.com", AutoExtractArticleListData)
@override_for("au.example.com", AutoExtractArticleListData)
@override_for("fr.example.com", AutoExtractArticleListData)
```

It will allow other interesting combinations like:

```py
@override_for("example.com", AutoExtractArticleListData)
@override_for("example.com/deals", AutoExtractArticleListData)
```

or 

```py
@override_for("example.com", AutoExtractArticleListData)
@override_for("ie.example.com", AutoExtractArticleListData)
```

Feel free to review the PR if you want and have the time: comments are always welcome :-)
