### ISSUE TITLE
Add ResponseUrl provider

### ISSUE THREAD

**Issue by kmike** [scrapinghub/scrapy-poet#83]
A basic implementation should be pretty straightforward. 

But I wonder if current scrapy-poet providers API is powerful enough to support further iterations of ResponseUrl. 
For example, let's say there is a base class defined:

```py
import attrs
from zyte_common_items import Product
from web_poet import ItemPage, field, ResponseUrl

@attrs.define
class ProductPage(ItemPage[Product]):
    response_url: ResponseUrl

    @field
    def url(self):
        return self.response_url
```

Ideally, if HttpResponse is a dependency, its URL should be used. But if BrowserHtml is a dependency, we should use its URL. So, it'd be great if the following works without downloading the page twice (with and without browser) - only browser should be used:

```py
@attrs.define
class ExampleProductPage(ProductPage):
    html: BrowserHtml
```

Solving the case above is not a requirement to have a basic ResponseUrl provider, but if anyone has any thoughts about it, please share :)

**Comment by BurnzZ** [comment]
> But if BrowserHtml is a dependency, we should use its URL.

Currently, [web_poet.BrowserHtml](https://github.com/scrapinghub/web-poet/blob/master/web_poet/page_inputs/browser.py) only holds a `str` value. Should we update it in `web-poet` to also hold a `ResponseUrl` as well?

**Comment by kmike** [comment]
> Currently, [web_poet.BrowserHtml](https://github.com/scrapinghub/web-poet/blob/master/web_poet/page_inputs/browser.py) only holds a str value. Should we update it in web-poet to also hold a ResponseUrl as well?

We have 2 options:

1) Add something like BrowserResponse, which contains BrowserHtml and ResponseUrl
2) Add url attribute to BrowserHtml

(1) seems more consistent with how we handle HttpResponse - there is HttpResponseBody, which is similar in nature to BrowserHtml.
