### ISSUE TITLE
Add tests that ensure transitive property of `instead_of` works.

### ISSUE THREAD

**Issue by BurnzZ** [scrapinghub/scrapy-poet#90]
Stemming from: https://github.com/scrapinghub/web-poet/pull/84#discussion_r1004807507

@Gallaecio had brought up a good point:
> I also wonder what happens when you have 2 levels of `instead_of`. If you have a `@handle_urls` decorator on `B` with `instead_of=A`, and on `C` with `instead_of=B`, is `B` used or is it `C`? Do we have a test for this?

Some tests should be written to ensure the expected behavior on this, as well as if the priority values are respected.

**Comment by BurnzZ** [comment]
Added a test in https://github.com/scrapinghub/scrapy-poet/pull/88.

Currently, there's no transitivity that happens for this: `A -> B -> C`. So if `A` is being required, `C` wouldn't be used as an override, but rather `B`.

There are use cases that merits the use of either behaviors. However, I think supporting transitive overrides makes the solution more complex. We could simply opt to create a rule that `C overrides A` to solve the problem.

**Comment by kmike** [comment]
I think not having such transitivity is fine. Let's close it.
