### ISSUE TITLE
HttpResponseProvider.fingerprint() broken?

### ISSUE THREAD

**Issue by wRAR** [scrapinghub/scrapy-poet#93]
When trying to run a simple spider with caching enabled I get this exception:

```Python traceback
File ".env/lib/python3.10/site-packages/scrapy_poet/page_input_providers.py", line 184, in fingerprint
  k: str(v) for k, v in request.to_dict().items() if k in request_keys
File ".env/lib/python3.10/site-packages/scrapy/http/request/__init__.py", line 184, in to_dict
  "callback": _find_method(spider, self.callback) if callable(self.callback) else self.callback,
File ".env/lib/python3.10/site-packages/scrapy/http/request/__init__.py", line 208, in _find_method
  raise ValueError(f"Function {func} is not an instance method in: {obj}")
```

So if the request has `callback` set, `to_dict()` expects a spider object which isn't passed here. Not sure whether it worked originally, before #74. It's also possible I'm just doing something wrong.

Note that the comment in `Request.to_dict()` is misleading, but it was always that way since `scrapy.utils.reqser.request_to_dict()` was introduced and is probably a copypasting error from `request_from_dict()`.

A minimal spider:

```Python
import scrapy
from web_poet.pages import ItemWebPage


class BookPage(ItemWebPage):
    def to_item(self):
        return {
            'url': self.url,
        }


class BooksSpider(scrapy.Spider):
    name = 'poet1'
    start_urls = ['http://books.toscrape.com/']

    custom_settings = dict(
        DOWNLOADER_MIDDLEWARES={
            'scrapy_poet.InjectionMiddleware': 543,
        },
        SPIDER_MIDDLEWARES={
            "scrapy_poet.RetryMiddleware": 275,
        }
    )

    def parse_book(self, response, book_page: BookPage):
        yield book_page.to_item()

    def parse(self, response):
        links = response.css('.image_container a')
        yield from response.follow_all(links, self.parse_book)
```

Run it with `-s SCRAPY_POET_CACHE=foo.sqlite`

**Comment by Gallaecio** [comment]
Related, although no need to handle it as part of this ticket unless trivial: we should use centralized request fingerprinting, as introduced in Scrapy 2.7.

**Comment by kmike** [comment]
@Gallaecio why should we use centralized fingerprints for fingerprints of page object dependencies?

**Comment by Gallaecio** [comment]
I did not think too hard about it. I was thinking of potential issues when using scrapy-poet and scrapy-zyte-api in combination, but I guess it will not necessarily involve different meta parameters on requests that are otherwise the same.
